import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
}

// Single source of truth for the app version — consumed by nativeDistributions AND
// generated into AppBuildConfig.kt so UI code never restates it as a string literal.
val dexVersionName = "1.0.0"

// Repo identity for the About surfaces, same single-source treatment.
val dexRepoUrl = "https://github.com/SplashCodeDex/DeX"

// Generates com.dexstudios.dex.AppBuildConfig from the values above at build time,
// mirroring Android's BuildConfig so Kotlin code reads one canonical object.
val generateDexBuildConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/dexBuildConfig")
    val version = dexVersionName
    val repoUrl = dexRepoUrl
    outputs.dir(outputDir)
    inputs.property("dexVersionName", version)
    inputs.property("dexRepoUrl", repoUrl)
    doLast {
        val dir = outputDir.get().asFile.resolve("com/dexstudios/dex")
        dir.mkdirs()
        File(dir, "AppBuildConfig.kt").writeText(
            """
            |package com.dexstudios.dex
            |
            |/**
 * GENERATED by the generateDexBuildConfig task — do not edit.
 * Values originate from composeApp/build.gradle.kts (dexVersionName / dexRepoUrl).
 */
object AppBuildConfig {
    const val VERSION_NAME = "$version"
    const val REPO_URL = "$repoUrl"
}
            """.trimMargin(),
        )
    }
}

kotlin {
    jvm("desktop")

    sourceSets {
        val desktopMain = getByName("desktopMain")
        // Generated AppBuildConfig source root; the mapped provider wires the
        // generateDexBuildConfig dependency into every compile of this source set.
        desktopMain.kotlin.srcDir(generateDexBuildConfig.map { it.outputs.files.first() })

        commonMain.dependencies {
            implementation(libs.kermit)
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.components.uiToolingPreview)

            implementation(libs.androidx.lifecycle.viewmodel.compose.multiplatform)
            implementation(libs.androidx.navigation.compose)
            implementation(libs.androidx.datastore.preferences)

            implementation(project(":core:network"))
            implementation(project(":core:data"))
            implementation(project(":core:designsystem"))
            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)

            implementation(libs.kotlinx.serialization.json)
            implementation(libs.qrcode.kotlin)
            implementation(libs.coil.compose)
            implementation(libs.compottie)
        }

        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.compose.native.tray)
            implementation(libs.coroutines.swing)
            implementation(libs.ktor.client.cio)
            implementation(libs.ktor.server.core)
            implementation(libs.ktor.server.netty)
            implementation(libs.ktor.server.websockets)
            implementation(libs.ktor.server.content.negotiation)
            implementation(libs.jna)
            implementation(libs.jna.platform)
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.mockk)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.dexstudios.dex.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "DeX"
            packageVersion = dexVersionName

            macOS {
                bundleID = "com.dexstudios.dex"
                appCategory = "public.app-category.utilities"
                // iconFile.set(project.file("src/desktopMain/resources/icon.icns"))
            }

            windows {
                menuGroup = "DeX Studios"
                upgradeUuid = "6ac1f203-bde0-4040-a2f3-f8a6dcda330c"
                dirChooser = true
                shortcut = true
                iconFile.set(project.file("src/desktopMain/resources/icon.ico"))
            }
        }
    }
}
